return {
  "andweeb/presence.nvim",
  opts = {
    auto_update = true,
    neovim_image_text = "Best editor in the world",
    main_image = "neovim",
    client_id = "793271441293967371",
    log_level = nil,
    debounce_timeout = 10,
    enable_line_number = false,
    blacklist = {},
    buttons = true,
    file_assets = {},
    show_time = true,
    editing_text = "vim과 함께 코딩중...",
    file_explorer_text = "vim과 함께 파일 탐색중...",
    git_commit_text = "Committing changes",
    plugin_manager_text = "Managing plugins",
    reading_text = "vim과 함께 글 읽는 중...",
    workspace_text = "Secret Project",
    line_number_text = "vim과 함께 중요한 부분 보는중...",
  },
}
